apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: boot-app
  template:
    metadata:
      labels:
        run: boot-app
    spec:
      containers:
      - name: boot-app
        image: bootdemo:1
        resources:
          limits:
            memory: "1000Mi"
            cpu: "500m"
        ports:
          - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: bootapp-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    run: boot-app
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30003